### PR TITLE
chore: use one function to handler all vpn configs

### PR DESCRIPTION
**Pull request by AmirAref**

### CODE REVIEW

**Comment by MortezaBashsiz** [comment]
I have tested and failed when I push the get new vpn
ایران-داخلی
آلمان-.....

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/python_telegram_bot-20.0a6-py3.9.egg/telegram/ext/_application.py", line 1057, in process_update
    await coroutine
  File "/usr/local/lib/python3.9/dist-packages/python_telegram_bot-20.0a6-py3.9.egg/telegram/ext/_conversationhandler.py", line 824, in handle_update
    new_state: object = await handler.handle_update(
  File "/usr/local/lib/python3.9/dist-packages/python_telegram_bot-20.0a6-py3.9.egg/telegram/ext/_handler.py", line 143, in handle_update
    return await self.callback(update, context)
  File "/tmp/Sudoer_VPN_bot/bot.py", line 289, in get_config
    region = query.split(':')[1]
AttributeError: 'CallbackQuery' object has no attribute 'split'
```

**Comment by AmirAref** [comment]
the error has been fixed right now.

**Comment by MortezaBashsiz** [comment]
Thanks
It also not work fine for Iran urls 
Please check this function

```python
def get_url_byzone(conn, zone):
    print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
    print(zone)
```
zone here is ARV and should be one of the list

**Comment by AmirAref** [comment]
oh sorry, i figured it this now and fixed, check it.

**Pull request merged**
